/**:
  ros__parameters:
    use_ignition_tf: False
    mocap_topic: "/optitrack/rigid_bodies"
    twist_smooth_filter_cte: 0.1
    orientation_smooth_filter_cte: 0.1

/tello1/state_estimator:
  ros__parameters:
    rigid_body_name: "tello1"

/tello2/state_estimator:
  ros__parameters:
    rigid_body_name: "tello2"

/tello3/state_estimator:
  ros__parameters:
    rigid_body_name: "tello3"